apiVersion: apps/v1
kind: Deployment
metadata:
  name: webproject
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: webproject
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: webproject
    spec:
      containers:
      - name: webproject
        image: meraazregistry.azurecr.io/webserver:web14  
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: azuresecret 

---
apiVersion: v1
kind: Service
metadata:
  name: webproject
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: webproject
